version: '3'
services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_HOST: ${DB_HOST:-localhost}
    network_mode: "host"
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  web:
    build: .
    depends_on:
      - db
    environment:
      MIX_ENV: dev
    env_file:
      - .env.dev
    ports:
      - '4000:4000'
    volumes:
      - ./:/app
      - /app/_build
      - /app/deps
      - /app/priv/uploads

volumes:
  db:
    driver: local
